apiVersion: v1
kind: Service
metadata:
  name: hello-world-flask-service
  labels:
    app: hello-world-flask
spec:
  selector:
    app: hello-world-flask
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
